/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeaRouteImport } from './routes/tea'
import { Route as GameRouteImport } from './routes/game'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationRouteRouteImport } from './routes/Application/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductPidRouteImport } from './routes/Product.$pid'
import { Route as ApplicationDashboardRouteImport } from './routes/Application/Dashboard'

const ProductsLazyRouteImport = createFileRoute('/Products')()

const ProductsLazyRoute = ProductsLazyRouteImport.update({
  id: '/Products',
  path: '/Products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Products.lazy').then((d) => d.Route))
const TeaRoute = TeaRouteImport.update({
  id: '/tea',
  path: '/tea',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRouteRoute = ApplicationRouteRouteImport.update({
  id: '/Application',
  path: '/Application',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPidRoute = ProductPidRouteImport.update({
  id: '/Product/$pid',
  path: '/Product/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationDashboardRoute = ApplicationDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => ApplicationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Application': typeof ApplicationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/tea': typeof TeaRoute
  '/Products': typeof ProductsLazyRoute
  '/Application/Dashboard': typeof ApplicationDashboardRoute
  '/Product/$pid': typeof ProductPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Application': typeof ApplicationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/tea': typeof TeaRoute
  '/Products': typeof ProductsLazyRoute
  '/Application/Dashboard': typeof ApplicationDashboardRoute
  '/Product/$pid': typeof ProductPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Application': typeof ApplicationRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/tea': typeof TeaRoute
  '/Products': typeof ProductsLazyRoute
  '/Application/Dashboard': typeof ApplicationDashboardRoute
  '/Product/$pid': typeof ProductPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Application'
    | '/about'
    | '/game'
    | '/tea'
    | '/Products'
    | '/Application/Dashboard'
    | '/Product/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Application'
    | '/about'
    | '/game'
    | '/tea'
    | '/Products'
    | '/Application/Dashboard'
    | '/Product/$pid'
  id:
    | '__root__'
    | '/'
    | '/Application'
    | '/about'
    | '/game'
    | '/tea'
    | '/Products'
    | '/Application/Dashboard'
    | '/Product/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationRouteRoute: typeof ApplicationRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GameRoute: typeof GameRoute
  TeaRoute: typeof TeaRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  ProductPidRoute: typeof ProductPidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Products': {
      id: '/Products'
      path: '/Products'
      fullPath: '/Products'
      preLoaderRoute: typeof ProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tea': {
      id: '/tea'
      path: '/tea'
      fullPath: '/tea'
      preLoaderRoute: typeof TeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Application': {
      id: '/Application'
      path: '/Application'
      fullPath: '/Application'
      preLoaderRoute: typeof ApplicationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Product/$pid': {
      id: '/Product/$pid'
      path: '/Product/$pid'
      fullPath: '/Product/$pid'
      preLoaderRoute: typeof ProductPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Application/Dashboard': {
      id: '/Application/Dashboard'
      path: '/Dashboard'
      fullPath: '/Application/Dashboard'
      preLoaderRoute: typeof ApplicationDashboardRouteImport
      parentRoute: typeof ApplicationRouteRoute
    }
  }
}

interface ApplicationRouteRouteChildren {
  ApplicationDashboardRoute: typeof ApplicationDashboardRoute
}

const ApplicationRouteRouteChildren: ApplicationRouteRouteChildren = {
  ApplicationDashboardRoute: ApplicationDashboardRoute,
}

const ApplicationRouteRouteWithChildren =
  ApplicationRouteRoute._addFileChildren(ApplicationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationRouteRoute: ApplicationRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GameRoute: GameRoute,
  TeaRoute: TeaRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  ProductPidRoute: ProductPidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
